isabelle:
  master_dir: 'formalisation/isabelle'

gpt-3.5-turbo:
  engine: gpt-3.5-turbo
  api_key: your_api_key_here

gpt-4o:
  engine: gpt-4o
  api_key: your_api_key_here

gpt-4o-mini:
  engine: gpt-4o-mini
  api_key: your_api_key_here

huggingface:
  api_key: your_hf_token_here
